function clean(v,max=5000){return typeof v==="string"?v.trim().slice(0,max):""}
function serverHeaders(key){const h={apikey:key,"Content-Type":"application/json"};if(!key.startsWith("sb_secret_"))h.Authorization=`Bearer ${key}`;return h}
function safeJson(value,depth=0){if(depth>6)return null;if(Array.isArray(value))return value.slice(0,60).map(v=>safeJson(v,depth+1));if(value&&typeof value==="object"){const out={};for(const [k,v] of Object.entries(value).slice(0,100))if(/^[a-z][a-z0-9_]{0,60}$/i.test(k))out[k]=safeJson(v,depth+1);return out}if(typeof value==="string")return value.trim().slice(0,5000);if(typeof value==="boolean"||typeof value==="number")return value;return null}
async function staff(req,url,key){const auth=clean(req.headers.authorization,5000);if(!auth.startsWith("Bearer "))return null;const ur=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:auth}});if(!ur.ok)return null;const user=await ur.json();const rr=await fetch(`${url}/rest/v1/staff_roles?id=eq.${encodeURIComponent(user.id)}&select=role&limit=1`,{headers:serverHeaders(key)});if(!rr.ok)return null;const roles=await rr.json();if(!roles[0]||!["admin","staff"].includes(roles[0].role))return null;return{user,role:roles[0].role}}
async function rows(url,key,query=""){const r=await fetch(`${url}/rest/v1/site_content?select=*${query}`,{headers:serverHeaders(key)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(`Site CMS table error: ${JSON.stringify(d)}`);return d||[]}
export default async function handler(req,res){
  res.setHeader("X-Content-Type-Options","nosniff");
  if(!["GET","PUT","POST"].includes(req.method)){res.setHeader("Allow","GET, PUT, POST");return res.status(405).json({error:"Method not allowed."})}
  const url=clean(process.env.SUPABASE_URL,500).replace(/\/$/,"");const key=clean(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY,5000);if(!url||!key)return res.status(503).json({error:"Site CMS is not configured."});
  try{
    if(req.method==="GET"){
      const wantsAdmin=req.query?.admin==="1"||new URL(req.url||"/",`https://${req.headers.host||"localhost"}`).searchParams.get("admin")==="1";
      if(!wantsAdmin){res.setHeader("Cache-Control","public, s-maxage=60, stale-while-revalidate=300");const data=await rows(url,key);const content={};data.forEach(r=>{if(r.published_at&&r.published_content)content[r.content_key]=r.published_content});return res.status(200).json({content,published_at:data.reduce((m,r)=>!m||r.published_at>m?r.published_at:m,null)})}
      const member=await staff(req,url,key);if(!member)return res.status(401).json({error:"Staff authorization required."});res.setHeader("Cache-Control","no-store");const data=await rows(url,key,"&order=content_key.asc");let history=[];const hr=await fetch(`${url}/rest/v1/site_content_history?select=id,content_key,action,changed_by,created_at&order=created_at.desc&limit=50`,{headers:serverHeaders(key)});if(hr.ok)history=await hr.json();return res.status(200).json({sections:data,history,role:member.role});
    }
    const member=await staff(req,url,key);if(!member)return res.status(401).json({error:"Staff authorization required."});const headers=serverHeaders(key);
    if(req.method==="PUT"){
      const contentKey=clean(req.body?.content_key,100);if(!/^(homepage|global)\.[a-z0-9_.-]+$/i.test(contentKey))return res.status(400).json({error:"Invalid content key."});const content=safeJson(req.body?.content);if(!content||typeof content!=="object")return res.status(400).json({error:"Invalid content."});
      const record={content_key:contentKey,draft_content:content,updated_by:member.user.id,updated_at:new Date().toISOString()};const up=await fetch(`${url}/rest/v1/site_content?on_conflict=content_key`,{method:"POST",headers:{...headers,Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(record)});const data=await up.json().catch(()=>null);if(!up.ok)return res.status(502).json({error:"Could not save draft. Run supabase/site_cms.sql."});const row=data?.[0];if(row)await fetch(`${url}/rest/v1/site_content_history`,{method:"POST",headers,body:JSON.stringify({content_id:row.id,content_key:contentKey,content,action:"draft_saved",changed_by:member.user.id})});return res.status(200).json({section:row});
    }
    const action=clean(req.body?.action,40);
    if(action==="publish"||action==="publish_all"){
      if(member.role!=="admin")return res.status(403).json({error:"Only administrators can publish."});const contentKey=clean(req.body?.content_key,100);const selected=action==="publish_all"?await rows(url,key):await rows(url,key,`&content_key=eq.${encodeURIComponent(contentKey)}&limit=1`);if(!selected.length)return res.status(404).json({error:"No draft section found."});const published=[];for(const row of selected){const now=new Date().toISOString();const patch={published_content:row.draft_content,published_at:now,published_by:member.user.id,updated_at:now};const pr=await fetch(`${url}/rest/v1/site_content?id=eq.${row.id}&select=*`,{method:"PATCH",headers:{...headers,Prefer:"return=representation"},body:JSON.stringify(patch)});const pd=await pr.json().catch(()=>null);if(!pr.ok)throw new Error("Publish failed");await fetch(`${url}/rest/v1/site_content_history`,{method:"POST",headers,body:JSON.stringify({content_id:row.id,content_key:row.content_key,content:row.draft_content,action:"published",changed_by:member.user.id})});published.push(pd?.[0]||patch)}return res.status(200).json({published});
    }
    if(action==="rollback"){
      if(member.role!=="admin")return res.status(403).json({error:"Only administrators can roll back."});const historyId=clean(req.body?.history_id,60);const hr=await fetch(`${url}/rest/v1/site_content_history?id=eq.${encodeURIComponent(historyId)}&select=*&limit=1`,{headers});const hs=await hr.json();const item=hs?.[0];if(!item)return res.status(404).json({error:"Revision not found."});const current=await rows(url,key,`&content_key=eq.${encodeURIComponent(item.content_key)}&limit=1`);if(!current[0])return res.status(404).json({error:"Section not found."});const patch={draft_content:item.content,published_content:item.content,published_at:new Date().toISOString(),published_by:member.user.id,updated_by:member.user.id};const pr=await fetch(`${url}/rest/v1/site_content?id=eq.${current[0].id}&select=*`,{method:"PATCH",headers:{...headers,Prefer:"return=representation"},body:JSON.stringify(patch)});const pd=await pr.json();await fetch(`${url}/rest/v1/site_content_history`,{method:"POST",headers,body:JSON.stringify({content_id:current[0].id,content_key:item.content_key,content:item.content,action:"rolled_back",changed_by:member.user.id})});return res.status(200).json({section:pd?.[0]});
    }
    return res.status(400).json({error:"Unknown action."});
  }catch(error){console.error("Site CMS",error);return res.status(502).json({error:"Site CMS request failed. Confirm the CMS SQL migration and server variables."})}
}
