import { randomUUID } from "node:crypto";
function clean(v,max=1000){return typeof v==="string"?v.trim().slice(0,max):""}
function headers(key){const h={apikey:key};if(!key.startsWith("sb_secret_"))h.Authorization=`Bearer ${key}`;return h}
async function admin(req,url,key){const a=clean(req.headers.authorization,5000);if(!a.startsWith("Bearer "))return null;const ur=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:a}});if(!ur.ok)return null;const user=await ur.json();const rr=await fetch(`${url}/rest/v1/staff_roles?id=eq.${user.id}&select=role&limit=1`,{headers:headers(key)});if(!rr.ok)return null;const roles=await rr.json();return roles[0]?.role==="admin"?user:null}
export default async function handler(req,res){
  res.setHeader("Cache-Control","no-store");if(!["GET","POST","DELETE"].includes(req.method)){res.setHeader("Allow","GET, POST, DELETE");return res.status(405).json({error:"Method not allowed."})}
  const url=clean(process.env.SUPABASE_URL,500).replace(/\/$/,"");const key=clean(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY,5000);if(!url||!key)return res.status(503).json({error:"Media storage is not configured."});const user=await admin(req,url,key);if(!user)return res.status(401).json({error:"Administrator authorization required."});const h=headers(key);
  try{
    if(req.method==="GET"){const r=await fetch(`${url}/rest/v1/site_media_assets?select=*&order=created_at.desc&limit=200`,{headers:h});const d=await r.json();if(!r.ok)throw new Error("list failed");return res.status(200).json({assets:d})}
    if(req.method==="DELETE"){const id=clean(req.body?.id,60);const lr=await fetch(`${url}/rest/v1/site_media_assets?id=eq.${id}&select=*`,{headers:h});const rows=await lr.json();const asset=rows?.[0];if(!asset)return res.status(404).json({error:"Asset not found."});await fetch(`${url}/storage/v1/object/site-media/${asset.storage_path}`,{method:"DELETE",headers:h});await fetch(`${url}/rest/v1/site_media_assets?id=eq.${id}`,{method:"DELETE",headers:h});return res.status(200).json({deleted:true})}
    const name=clean(req.body?.file_name,200).replace(/[^a-zA-Z0-9._-]/g,"-");const type=clean(req.body?.content_type,100);const encoded=clean(req.body?.data_base64,8000000);const allowed=new Set(["image/jpeg","image/png","image/webp","image/gif"]);if(!name||!allowed.has(type)||!encoded)return res.status(400).json({error:"Choose a JPEG, PNG, WebP or GIF image."});const buffer=Buffer.from(encoded.replace(/^data:[^;]+;base64,/,""),"base64");if(!buffer.length||buffer.length>5242880)return res.status(400).json({error:"Image must be 5 MB or smaller."});const ext=(name.split(".").pop()||"jpg").toLowerCase();const storagePath=`${new Date().toISOString().slice(0,10)}/${randomUUID()}.${ext}`;const upload=await fetch(`${url}/storage/v1/object/site-media/${storagePath}`,{method:"POST",headers:{...h,"Content-Type":type,"x-upsert":"false"},body:buffer});if(!upload.ok){console.error("Media upload",upload.status,await upload.text());return res.status(502).json({error:"Supabase media upload failed. Run supabase/site_cms.sql."})}const publicUrl=`${url}/storage/v1/object/public/site-media/${storagePath}`;const record={file_name:name,storage_path:storagePath,public_url:publicUrl,content_type:type,size_bytes:buffer.length,alt_text:clean(req.body?.alt_text,500)||null,uploaded_by:user.id};const ir=await fetch(`${url}/rest/v1/site_media_assets`,{method:"POST",headers:{...h,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify(record)});const data=await ir.json();return res.status(201).json({asset:data?.[0]||record})
  }catch(error){console.error("Site media",error);return res.status(502).json({error:"Media library request failed."})}
}
